# Generated by Django 5.2.12 on 2026-03-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countrygroup',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterField(
            model_name='countrygroup',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null = global group type (e.g. World Bank)', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.RemoveField(
            model_name='countrygroup',
            name='type',
        ),
        migrations.DeleteModel(
            name='CountryGroupType',
        ),
    ]
