# Generated by Django 4.2.29 on 2026-03-10 15:36

import datafiles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the datafile, required', max_length=255)),
                ('contact', models.CharField(blank=True, help_text='email or name of contact person who provided datafile', max_length=255)),
                ('description', models.TextField(blank=True, help_text='description of the datafile')),
                ('notes', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('raw', 'Raw'), ('cleaned', 'Cleaned'), ('etl', 'Etl'), ('other', 'Other'), ('tableau', 'Tableau')], default='other', max_length=50)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=datafiles.models.get_upload_path)),
                ('previous_file_path', models.FileField(blank=True, null=True, upload_to=datafiles.models.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('header_row', models.IntegerField(default=0)),
                ('raw_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned', to='datafiles.datafile')),
            ],
        ),
    ]
